export const CONCEAL_METHODS = {
    BASE64: 'Base64',
    MD5: 'MD5',
    SHA256: 'SHA256',
    AES: 'AES'
};

export const REVEAL_METHODS = {
    BASE64: 'Base64',
    AES: 'AES'
};

export const LCBO_ACCESS_KEY = "MDo4Mjg3MDljOC04YjZhLTExZTYtOWVkNC00ZmIyNjBmZDA0MWY6a0xDbElDU3lJdXVLVUhKR3BmN0ZrTUpWRTFLSnc3TU5HOEF6";